[package]
name = "Manji"
version = "0.1.0"
edition = "2024"
authors = ["Hamid Bahrami"]

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "Manji"
path = "src/main.rs"
test = false
bench = false